### PR TITLE
Resolved issue #4

### PR DESCRIPTION
**Pull request by thompsonemerson**
demo resolved:

### CODE REVIEW

**Comment by felipesousa** [comment]
👍

**Comment by kandebonfim** [comment]
Nice touch, @thompsonemerson! I'm not sure why is that happening but seems like a good idea to set `min-height` instead of `height`. 👍  :shipit:

**Comment by kandebonfim** [comment]
Thanks, @thompsonemerson @felipesousa!

**Comment by thompsonemerson** [comment]
@kandebonfim with min-height you set the initial value of height. 🚀  beautiful work!

**Comment by felipesousa** [comment]
🎯

**Comment by kandebonfim** [comment]
[Off topic] This repo reached the 8th place in github trending javascript repos today.

https://github.com/trending/javascript

**Pull request merged**
